In [1]:
import numpy as np

array = np.arange(10)

print(array)
print(type(array))
print(array.dtype)

[0 1 2 3 4 5 6 7 8 9]
<type 'numpy.ndarray'>
int64


In [2]:
array.shape

(10,)

In [4]:
float_arr = array / 2.0

print(float_arr)
print(type(float_arr))
print(float_arr.dtype)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5]
<type 'numpy.ndarray'>
float64


In [5]:
prices = np.array([1, 3, -2, 9, 5, 7, 2])

prices

array([ 1,  3, -2,  9,  5,  7,  2])

In [6]:
signal_one = prices > 2
signal_three = prices > 4

In [7]:
signal_one

array([False,  True, False,  True,  True,  True, False], dtype=bool)

In [8]:
signal_three

array([False, False, False,  True,  True,  True, False], dtype=bool)

In [9]:
signal_one.astype(np.int)


array([0, 1, 0, 1, 1, 1, 0])

In [10]:
signal_one=signal_one.astype(np.int)

In [11]:
signal_three=signal_three.astype(np.int)

In [12]:
pos1= 1 * signal_one

In [13]:
pos1

array([0, 1, 0, 1, 1, 1, 0])

In [14]:
pos3=3 * signal_three

In [15]:
pos3


array([0, 0, 0, 3, 3, 3, 0])

In [16]:
long_pos=pos1 + pos3

In [17]:
long_pos

array([0, 1, 0, 4, 4, 4, 0])

In [18]:
prices = np.array([123,45,65,11,9,45,33,77,23,12,87,342,89])

In [19]:
long_30=prices > 50
short_10=prices < 20


In [21]:
signal_short_10=short_10.astype(np.int)
signal_long_30=long_30.astype(np.int)

In [26]:
pos_30= 30 * signal_long_30
pos_10= -10 * signal_short_10

In [27]:
pos_30

array([30,  0, 30,  0,  0,  0,  0, 30,  0,  0, 30, 30, 30])

In [28]:
pos_10

array([  0,   0,   0, -10, -10,   0,   0,   0,   0, -10,   0,   0,   0])

In [29]:
pos_10+pos_30

array([ 30,   0,  30, -10, -10,   0,   0,  30,   0, -10,  30,  30,  30])